title: Tyler Hutton
repository: huttontyler/website  # <--- ADD THIS LINE
languages: ["de-ch", "en-gb"]
default_lang: "de-ch"
baseurl: "" 
url: "https://tylerhutton.ch" 
theme: jekyll-theme-primer

exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "vendor"]

# Social Media
bluesky_username: tylerhutton.ch
youtube_channel: huttontyler
linkedin_username: huttontyler
github_username: huttontyler

defaults:
  - scope:
      path: "de"
    values:
      lang: "de-ch"
  - scope:
      path: "en"
    values:
      lang: "en-gb"
